### ISSUE TITLE
Convert to using shared_configs

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-preservation-core#33]
TODO:
- [x] shared_configs are in:
  - https://github.com/sul-dlss/shared_configs/tree/sdr-preservation-core_dev
  - https://github.com/sul-dlss/shared_configs/tree/sdr-preservation-core_stage
  - https://github.com/sul-dlss/shared_configs/tree/sdr-preservation-core_prod
- [x] puppet deployment for shared_configs
  - @eefahy recommends that we don't hack puppet for this because it's not designed to work well with two apps deployed to the same system
  - add tasks to the capistrano-shared-configs gem:
    - https://github.com/sul-dlss/capistrano-shared_configs/pull/5
- [x] the sdr-preservation-core should contain capistrano deploy configs
  - [x] proposed changes are in PR #58 
- [x] the sdr-configs to be purged of any sdr-preservation-core configs
  - [x] proposed changes are in PR https://github.com/sul-dlss/sdr-configs/pull/6

Related issues
- https://github.com/sul-dlss/sdr-configs/issues/1

Blockers:
- [x] #30 requires bundle updates to resolve security vulnerabilities (capistrano uses bundle-audit and it fails because master branch has vulnerabilities), but this is complicated by various DLSS dependencies and working through these updates has already been done on the `develop` branch, but the current deployment systems are still running the `master` branch.  The work to merge `develop` into `master` is complicated because simple cherry-picks are often not working and there are conflicts between these branches - this work is tracked in various PRs that are trying to resolve conflicts in #34 and hopefully get #34 merged.
- [x] blockers should be resolved by #57 and #55

**Comment by darrenleeweber** [comment]
Remove:
-  config/deploy/server_settings.rb
- .gitignore ln6
- bin/sync_configs.sh

**Comment by darrenleeweber** [comment]
Ran `bundle exec cap integration deploy:check` for the master branch and bumped into a deprecation notice, i.e.
```
[Deprecation Notice] Future versions of Capistrano will not load the Git SCM
plugin by default. To silence this deprecation warning, add the following to
your Capfile after `require "capistrano/deploy"`:

    require "capistrano/scm/git"
    install_plugin Capistrano::SCM::Git
```
